// bt_utils.dart — Stateless math utilities (RSSI, hashing, bucketing).
// See zbg_proximity_plan.md §3.5 for full specification.

import 'dart:convert';
import 'dart:math' as math;

import 'package:crypto/crypto.dart';

/// Converts an RSSI reading (dBm) to an estimated distance in metres using
/// the log-distance path-loss model:
///
///   distance = 10 ^ ((txPower - rssi) / (10 * pathLossExp))
///
/// [txPower]     — calibrated RSSI measured at exactly 1 m from the device.
///                 -59 dBm is a reasonable BLE default; tune per device if needed.
/// [pathLossExp] — path-loss exponent. 2.0 = free space. Use 2.5–3.5 indoors.
///
/// Returns a value in metres. Always >= 0.
double rssiToMeters(
  int rssi, {
  int txPower = -59,
  double pathLossExp = 2.0,
}) {
  if (pathLossExp <= 0) return 0;
  return math.pow(10.0, (txPower - rssi) / (10.0 * pathLossExp)).toDouble();
}

/// Returns the simple arithmetic mean of [samples] as a double.
///
/// [samples] must not be empty; returns 0.0 defensively if it is.
double rollingAverage(List<int> samples) {
  if (samples.isEmpty) return 0.0;
  return samples.reduce((a, b) => a + b) / samples.length;
}

/// Computes a stable, short identifier for a Firebase UID suitable for
/// embedding in a BLE manufacturer-data payload.
///
/// Returns the first 8 bytes of the SHA-256 hash of [uid] (UTF-8 encoded)
/// as a lowercase hex string (16 characters).
///
/// The same function must be called both when building the advertisement
/// (sender) and when looking up a received hash in the peer registry
/// (receiver), so the mapping is bijective within the participant pool.
String hashUidForAdvertisement(String uid) {
  final bytes = utf8.encode(uid);
  final digest = sha256.convert(bytes);
  return digest.bytes
      .take(8)
      .map((b) => b.toRadixString(16).padLeft(2, '0'))
      .join();
}

// ---------------------------------------------------------------------------
// Identity UUID helpers (iOS peer identification)
// ---------------------------------------------------------------------------

// Fixed namespace prefix for per-user BLE identity UUIDs produced by this
// package. Any 128-bit UUID whose str128 starts with this prefix was generated
// by [hashToIdentityUuid] and can be decoded by [identityUuidToHash].
const String _kIdentityUuidPrefix = 'b1e54f00-0000-0000-';

/// Derives a stable BLE identity UUID from a 16-character UID hash hex string
/// (the output of [hashUidForAdvertisement]).
///
/// Returns a lowercase 128-bit UUID in the form:
///   `b1e54f00-0000-0000-HHHH-HHHHHHHHHHHH`
/// where H = hash bytes as lowercase hex.
///
/// **iOS peer identification strategy** — iOS silently drops manufacturer data
/// from outgoing BLE advertisements. Instead of manufacturer data, iOS devices
/// advertise this identity UUID as their only service UUID. The scanning peer
/// includes all registered peer identity UUIDs in the [FlutterBluePlus.startScan]
/// `withServices` filter so that iOS background scanning delivers results for
/// matching devices without needing a scan response or a GATT connection.
String hashToIdentityUuid(String hashHex) {
  assert(hashHex.length == 16, 'hashHex must be 16 hex chars (8 bytes)');
  return '$_kIdentityUuidPrefix${hashHex.substring(0, 4)}-${hashHex.substring(4)}';
}

/// Inverse of [hashToIdentityUuid].
///
/// Returns the 16-character hash hex string embedded in [uuid], or null if
/// [uuid] is not an identity UUID generated by this package.
///
/// [uuid] must be a lowercase 128-bit UUID string — use [Guid.str128] from
/// flutter_blue_plus to guarantee this format.
String? identityUuidToHash(String uuid) {
  if (!uuid.startsWith(_kIdentityUuidPrefix)) return null;
  // Suffix is 'XXXX-XXXXXXXXXXXX' — strip the dash to recover the 16-char hash.
  final suffix = uuid.substring(_kIdentityUuidPrefix.length);
  return suffix.replaceAll('-', '');
}

// ---------------------------------------------------------------------------

/// Truncates [ts] to the nearest [intervalSeconds] boundary (rounding down)
/// and returns the result as a UTC ISO-8601 string.
///
/// Used by [BtWriters] to compute deduplication document IDs. Both devices
/// detecting the same proximity event within the same interval window produce
/// the same document ID, so the later write overwrites the earlier one without
/// accumulating duplicate documents.
///
/// [intervalSeconds] should match [BluetoothProximityConfig.insideGeofenceRateS]
/// so that the dedup window aligns with the configured write rate — one
/// document is stored per write attempt rather than many writes collapsing
/// onto the same document.
///
/// Example (intervalSeconds=30):  14:37:52 UTC → "2026-02-23T14:37:30.000Z"
/// Example (intervalSeconds=180): 14:37:52 UTC → "2026-02-23T14:36:00.000Z"
String timeBucket(DateTime ts, int intervalSeconds) {
  final utc = ts.toUtc();
  final secondsIntoDay = utc.hour * 3600 + utc.minute * 60 + utc.second;
  final bucketStart = (secondsIntoDay ~/ intervalSeconds) * intervalSeconds;
  return DateTime.utc(utc.year, utc.month, utc.day)
      .add(Duration(seconds: bucketStart))
      .toIso8601String();
}
